# Use postgres/example user/password credentials
version: '3.1'

volumes:
  postgres-volume:
    external: false

services:

  postgres:
    image: postgres:9.6.21-alpine
    restart: always
    environment:
      TZ: 'America/Bogota'
      PGTZ: 'America/Bogota'
      POSTGRES_USER: bigdata
      POSTGRES_PASSWORD: bigdata
      POSTGRES_DB: bigdata
    container_name: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  adminer-postgres:
    image: adminer:4.8.0
    container_name: adminer-postgres
    depends_on:
      - postgres
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 8082:8080